/* YKS konu listeleri (genel müfredat bilgisi; kişiye özel veri değildir).
   MEB ders programlarının ünite sırasına göre, yaygın YKS kaynaklarıyla çapraz kontrol edilerek derlendi.
   Sıralama sınav sırası değil, öğrenme sırasıdır (9 → 12. sınıf).
   Not: TYT Geometri, Temel Matematik testinin; AYT Geometri, AYT Matematik testinin içindedir. */
window.YKS_TOPICS = {
  TYT: {
    'Türkçe': ['Sözcükte Anlam','Söz Yorumu, Deyim ve Atasözü','Cümlede Anlam','Cümle Yorumu','Paragrafta Konu ve Ana Düşünce','Paragrafta Yardımcı Düşünce','Paragrafta Anlatım Teknikleri','Paragrafta Düşünceyi Geliştirme Yolları','Paragrafta Yapı ve Anlatım Akışı','Ses Bilgisi','Yazım Kuralları','Noktalama İşaretleri','Sözcükte Yapı ve Ekler','Sözcük Türleri: İsim ve Zamir','Sıfat, Zarf, Edat, Bağlaç, Ünlem','Fiiller ve Fiilimsiler','Fiilde Çatı','Cümlenin Ögeleri','Cümle Türleri','Anlatım Bozuklukları','Sözel Mantık ve Akıl Yürütme'],
    'Temel Matematik': ['Temel Kavramlar','Sayı Basamakları','Bölme ve Bölünebilme Kuralları','EBOB - EKOK','Rasyonel Sayılar','Basit Eşitsizlikler','Mutlak Değer','Üslü Sayılar','Köklü Sayılar','Çarpanlara Ayırma','Oran - Orantı','Denklem Çözme','Sayı ve Kesir Problemleri','Yaş Problemleri','İşçi ve Havuz Problemleri','Hareket Problemleri','Yüzde, Kâr - Zarar Problemleri','Karışım Problemleri','Grafik ve Tablo Problemleri','Rutin Olmayan Problemler','Kümeler','Kartezyen Çarpım','Mantık','Fonksiyonlar','Polinomlar','İkinci Dereceden Denklemler','Permütasyon ve Kombinasyon','Olasılık','Veri ve İstatistik'],
    'Geometri': ['Doğruda Açılar','Üçgende Açılar','Dik Üçgen ve Pisagor Bağıntısı','Özel Üçgenler','İkizkenar ve Eşkenar Üçgen','Üçgende Açı - Kenar Bağıntıları','Üçgende Açıortay','Üçgende Kenarortay','Üçgende Eşlik ve Benzerlik','Üçgende Alan','Çokgenler','Dörtgenler','Paralelkenar ve Eşkenar Dörtgen','Dikdörtgen ve Kare','Yamuk','Deltoid','Çemberde Açı','Çemberde Uzunluk','Dairede Alan','Noktanın Analitiği','Doğrunun Analitiği','Prizmalar','Piramitler','Silindir, Koni ve Küre'],
    'Fizik': ['Fizik Bilimine Giriş','Madde ve Özellikleri','Hareket ve Kuvvet','Dinamik: Newton Yasaları','İş, Güç ve Enerji','Isı, Sıcaklık ve Genleşme','Elektrostatik','Basınç','Kaldırma Kuvveti','Dalgalar','Yay ve Su Dalgaları','Ses Dalgaları','Deprem Dalgaları','Elektrik Akımı ve Devreler','Mıknatıs ve Manyetik Alan','Işığın Yayılması ve Gölge','Düzlem ve Küresel Aynalar','Işığın Kırılması ve Mercekler','Renk Bilgisi'],
    'Kimya': ['Kimya Bilimi','Atomun Yapısı','Periyodik Sistem','Kimyasal Türler Arası Etkileşimler','Güçlü Etkileşimler: Kimyasal Bağlar','Zayıf Etkileşimler','Maddenin Hâlleri','Doğa ve Kimya','Kimyanın Temel Kanunları','Mol Kavramı','Kimyasal Tepkimeler ve Denklemleri','Kimyasal Hesaplamalar','Karışımlar','Çözeltiler ve Derişim','Karışımların Ayrılması','Asitler ve Bazlar','Tuzlar','Kimya Her Yerde'],
    'Biyoloji': ['Canlıların Ortak Özellikleri','Canlılardaki İnorganik Bileşikler','Canlılardaki Organik Bileşikler','Hücre ve Organeller','Hücre Zarından Madde Geçişi','Canlıların Sınıflandırılması','Canlı Âlemleri','Mitoz ve Eşeysiz Üreme','Mayoz ve Eşeyli Üreme','Kalıtımın Genel İlkeleri','Mendel Genetiği ve Çaprazlamalar','Eşeye Bağlı Kalıtım','Soy Ağacı ve Kan Grupları','Genetik Mühendisliği ve Biyoteknoloji','Ekosistem Ekolojisi','Madde Döngüleri ve Enerji Akışı','Güncel Çevre Sorunları'],
    'Tarih': ['Tarih Bilimi','İnsanlığın İlk Dönemleri','Orta Çağ\'da Dünya','İlk ve Orta Çağlarda Türk Dünyası','İslam Medeniyetinin Doğuşu','Türklerin İslamiyet\'i Kabulü','İlk Türk - İslam Devletleri','Türkiye Selçuklu Devleti','Beylikten Devlete Osmanlı','Dünya Gücü Osmanlı','Osmanlı Kültür ve Medeniyeti','Arayış Yılları: XVII. Yüzyıl','Avrupa ve Osmanlı: XVIII. Yüzyıl','En Uzun Yüzyıl','XX. Yüzyıl Başlarında Osmanlı','I. Dünya Savaşı','Millî Mücadele Hazırlık Dönemi','Kurtuluş Savaşı Cepheleri','Türk İnkılabı','Atatürk İlkeleri ve Atatürkçülük','Atatürk Dönemi Türk Dış Politikası','II. Dünya Savaşı ve Sonrası'],
    'Coğrafya': ['Doğa ve İnsan','Coğrafi Konum','Harita Bilgisi','Dünya\'nın Şekli ve Hareketleri','Atmosfer ve Sıcaklık','Basınç ve Rüzgârlar','Nem, Yağış ve İklim Tipleri','Türkiye\'nin İklimi','İç Kuvvetler ve Yer Şekilleri','Dış Kuvvetler ve Yer Şekilleri','Türkiye\'nin Yer Şekilleri','Kayaçlar ve Toprak','Su Kaynakları ve Türkiye\'nin Suları','Bitki Örtüsü ve Biyoçeşitlilik','Nüfus ve Nüfus Özellikleri','Göçler','Yerleşme','Doğal Kaynaklar ve Ekonomi','Türkiye\'de Tarım ve Hayvancılık','Türkiye\'de Madenler ve Enerji','Türkiye\'de Sanayi','Ulaşım, Ticaret ve Turizm','Bölgeler ve Ülkeler','Doğal Afetler','Çevre ve Toplum'],
    'Felsefe': ['Felsefenin Konusu ve Anlamı','Felsefi Düşüncenin Özellikleri','Felsefenin Diğer Alanlarla İlişkisi','Bilgi Felsefesi','Varlık Felsefesi','Ahlak Felsefesi','Sanat Felsefesi','Din Felsefesi','Siyaset Felsefesi','Bilim Felsefesi','MÖ 6. - MS 2. Yüzyıl Felsefesi','İlk Çağ Filozofları','MS 2. - MS 15. Yüzyıl Felsefesi','İslam ve Orta Çağ Felsefesi','15. - 17. Yüzyıl Felsefesi','18. - 19. Yüzyıl Felsefesi','20. Yüzyıl Felsefesi'],
    'Din Kültürü ve Ahlak Bilgisi': ['Bilgi ve İnanç','İslam\'da İnanç Esasları','Allah - İnsan İlişkisi','İslam ve İbadet','Namaz, Oruç, Zekât ve Hac','Gençlik ve Değerler','Ahlaki Tutum ve Davranışlar','Hz. Muhammed\'in Hayatı','Hz. Muhammed\'in Örnekliği','Kur\'an-ı Kerim\'in Temel Özellikleri','Kur\'an\'dan Mesajlar','Vahiy ve Akıl','İslam Düşüncesinde Yorum Biçimleri','İtikadi ve Fıkhi Yorumlar','Tasavvufi Yorumlar','Anadolu\'da İslam','İslam ve Bilim','Din, Kültür ve Medeniyet','Yahudilik ve Hristiyanlık','Hint ve Çin Dinleri','Güncel Dini Meseleler'],
  },
  AYT: {
    'Matematik': ['Temel Kavramlar ve Sayılar','Mutlak Değer, Üslü ve Köklü Sayılar','Çarpanlara Ayırma ve Denklemler','Oran - Orantı ve Problemler','Kümeler ve Mantık','Fonksiyonlar','Bileşke ve Ters Fonksiyon','Polinomlar','İkinci Dereceden Denklemler','Karmaşık Sayılar','İkinci Dereceden Eşitsizlikler','Parabol','Permütasyon ve Kombinasyon','Binom ve Olasılık','İstatistik','Trigonometri: Yönlü Açılar','Trigonometrik Fonksiyonlar','Toplam - Fark ve Yarım Açı Formülleri','Trigonometrik Denklemler','Logaritma','Diziler','Limit ve Süreklilik','Türev','Türevin Uygulamaları','Belirsiz İntegral','Belirli İntegral ve Alan Hesabı'],
    'Geometri': ['Üçgende Açı ve Kenar Bağıntıları','Özel Üçgenler ve Pisagor','Üçgende Açıortay ve Kenarortay','Üçgende Eşlik ve Benzerlik','Üçgende Alan','Paralelkenar ve Eşkenar Dörtgen','Dikdörtgen, Kare ve Yamuk','Deltoid ve Çokgenler','Çemberde Açı','Çemberde Uzunluk ve Teğet','Dairede Alan','Noktanın Analitiği','Doğrunun Analitiği','Çemberin Analitiği','Dönüşüm Geometrisi','Vektörler','Prizmalar','Piramitler','Silindir ve Koni','Küre','Katı Cisimlerde Alan ve Hacim','Konikler: Elips, Hiperbol, Parabol'],
    'Fizik': ['Vektörler ve Kuvvet Dengesi','Tork ve Denge','Kütle Merkezi','Basit Makineler','Bağıl Hareket','Newton\'un Hareket Yasaları','Sürtünme Kuvveti','Bir Boyutta Sabit İvmeli Hareket','İki Boyutta Hareket: Atışlar','Enerji ve Hareket','İtme ve Momentum','Elektriksel Kuvvet ve Elektrik Alan','Elektriksel Potansiyel','Düzgün Elektrik Alan ve Sığa','Manyetizma ve Manyetik Kuvvet','İndüksiyon ve Alternatif Akım','Transformatörler','Çembersel Hareket','Dönerek Öteleme, Açısal Momentum','Kütle Çekim ve Kepler Yasaları','Basit Harmonik Hareket','Dalga Mekaniği ve Kırınım','Doppler Olayı','Atom Fiziği ve Radyoaktivite','Modern Fizik: Özel Görelilik','Fotoelektrik Olay ve Compton','Modern Fiziğin Teknolojideki Kullanımı'],
    'Kimya': ['Modern Atom Teorisi','Periyodik Sistem ve Özellikler','Kimyasal Türler Arası Etkileşimler','Gazlar','Sıvı Çözeltiler ve Çözünürlük','Derişim ve Koligatif Özellikler','Kimyasal Tepkimelerde Enerji','Entalpi ve Hess Yasası','Kimyasal Tepkimelerde Hız','Kimyasal Tepkimelerde Denge','Sulu Çözelti Dengeleri: Asit - Baz','Çözünürlük Dengesi','Kimya ve Elektrik','İndirgenme - Yükseltgenme Tepkimeleri','Elektrokimyasal Hücreler ve Elektroliz','Karbon Kimyasına Giriş','Hibritleşme ve Molekül Geometrisi','Organik Bileşikler: Hidrokarbonlar','Alkoller, Eterler ve Fenoller','Aldehit, Keton ve Karboksilik Asitler','Esterler','Enerji Kaynakları ve Bilimsel Gelişmeler','Kimya Her Yerde'],
    'Biyoloji': ['İnsan Fizyolojisine Giriş','Sinir Sistemi','Endokrin Sistem ve Hormonlar','Duyu Organları','Destek ve Hareket Sistemi','Sindirim Sistemi','Dolaşım ve Bağışıklık Sistemi','Solunum Sistemi','Üriner Sistem: Boşaltım','Üreme Sistemi ve Embriyonik Gelişim','Komünite Ekolojisi','Popülasyon Ekolojisi','Genden Proteine: Nükleik Asitler','DNA\'nın Replikasyonu','Protein Sentezi','Canlılarda Enerji Dönüşümleri','Fotosentez','Kemosentez','Hücresel Solunum','Bitkisel Dokular ve Organlar','Bitkilerde Madde Taşınması','Bitkilerde Büyüme ve Hareket','Bitkilerde Üreme','Canlılar ve Çevre'],
    'Türk Dili ve Edebiyatı': ['Güzel Sanatlar ve Edebiyat','Metinlerin Sınıflandırılması','Şiir Bilgisi ve Ölçü','Söz Sanatları','Anlatım Biçimleri ve Düşünce Yolları','İslamiyet Öncesi Türk Edebiyatı','Geçiş Dönemi Türk Edebiyatı','Anonim Halk Edebiyatı','Âşık Tarzı Halk Edebiyatı','Dinî - Tasavvufi Halk Edebiyatı','Divan Edebiyatı: Nazım Biçimleri','Divan Edebiyatı: Nazım Türleri','Divan Edebiyatı Şair ve Yazarları','Tanzimat Dönemi Edebiyatı','Servet-i Fünûn Edebiyatı','Fecr-i Âti Edebiyatı','Millî Edebiyat Dönemi','Cumhuriyet Dönemi Türk Şiiri','Beş Hececiler ve Yedi Meşaleciler','Garip ve İkinci Yeni','Cumhuriyet Dönemi Roman ve Hikâyesi','Cumhuriyet Dönemi Tiyatrosu','Edebî Akımlar','Dünya Edebiyatı','Öğretici Metinler ve Türleri'],
    'Tarih': ['Tarih ve Zaman','İnsanlığın İlk Dönemleri','Orta Çağ\'da Dünya','İlk ve Orta Çağlarda Türk Dünyası','İslam Medeniyetinin Doğuşu','Türklerin İslamiyet\'i Kabulü','Yerleşme ve Devletleşme: Selçuklu','Beylikten Devlete Osmanlı','Devletleşme Sürecinde Savaşçılar','Dünya Gücü Osmanlı','Sultan ve Osmanlı Merkez Teşkilatı','Klasik Çağda Osmanlı Toplum Düzeni','Değişen Dünya Dengeleri','Değişim Çağında Avrupa ve Osmanlı','Uluslararası İlişkilerde Denge','Devrimler Çağında Devlet ve Toplum','Sermaye ve Emek','XX. Yüzyıl Başlarında Osmanlı','Millî Mücadele','Atatürkçülük ve Türk İnkılabı','İki Savaş Arasında Türkiye ve Dünya','II. Dünya Savaşı Sürecinde Türkiye','Soğuk Savaş Dönemi','Yumuşama Dönemi ve Sonrası','Küreselleşen Dünya'],
    'Coğrafya': ['Ekosistem ve Madde Döngüleri','Biyoçeşitlilik','Nüfus Politikaları','Şehirlerin Fonksiyonları ve Nüfusu','Ekonomik Faaliyetlerin Sınıflandırması','Göç ve Şehirleşme','Türkiye\'de Nüfus ve Yerleşme','Türkiye\'nin Ekonomi Politikaları','Türkiye\'de Tarım ve Hayvancılık','Türkiye\'de Madenler ve Enerji','Türkiye\'de Sanayi','Türkiye\'de Ulaşım ve Ticaret','Türkiye\'de Turizm','Türkiye\'nin Jeopolitik Konumu','İlk Medeniyetler ve Şehirler','Kültür Bölgeleri ve Türk Kültürü','Küresel ve Bölgesel Örgütler','Ülkeler Arası Etkileşim','Bölgeler ve Bölge Türleri','Dünyada Üretim ve Ulaşım Ağları','Doğal Afetler ve Türkiye','Çevre Sorunları ve Kaynak Yönetimi','Ortak Doğal ve Kültürel Miras'],
    'Felsefe Grubu': ['Felsefenin Konusu ve Alanları','Bilgi Felsefesi','Varlık Felsefesi','Ahlak Felsefesi','Sanat Felsefesi','Din Felsefesi','Siyaset Felsefesi','Bilim Felsefesi','MÖ 6. - MS 2. Yüzyıl Felsefesi','MS 2. - MS 15. Yüzyıl Felsefesi','15. - 17. Yüzyıl Felsefesi','18. - 19. Yüzyıl Felsefesi','20. Yüzyıl Felsefesi','Psikoloji Bilimini Tanıyalım','Psikolojinin Temel Süreçleri','Duyum, Algı ve Dikkat','Öğrenme, Bellek ve Düşünme','Güdü ve Duygular','Ruh Sağlığının Temelleri','Sosyolojiye Giriş','Birey ve Toplum','Toplumsal Yapı ve Tabakalaşma','Toplumsal Değişme ve Gelişme','Toplum ve Kültür','Toplumsal Kurumlar','Mantığa Giriş','Klasik Mantık ve Kavramlar','Önermeler ve Kıyas','Mantık ve Dil','Sembolik Mantık'],
    'Din Kültürü ve Ahlak Bilgisi': ['Dünya ve Ahiret','Kur\'an\'a Göre Hz. Muhammed','Kur\'an\'da Bazı Kavramlar','Kur\'an\'dan Mesajlar','İnançla İlgili Meseleler','İslam ve İbadetler','Ahlaki Tutum ve Davranışlar','Allah - İnsan İlişkisi','Hz. Muhammed\'in Örnekliği','İslam Düşüncesinde Yorumlar','Tasavvufi Yorumlar','İslam ve Bilim','Anadolu\'da İslam','Yahudilik ve Hristiyanlık','Hint ve Çin Dinleri','Güncel Dini Meseleler'],
  },
  YDT: {
    'İngilizce': ['Tenses (Zamanlar)','Modals','Passive Voice ve Causatives','Gerunds ve Infinitives','Noun Clauses','Relative Clauses','Adverbial Clauses','Conditionals ve Wish Clauses','Conjunctions ve Transitions','Prepositions','Determiners ve Quantifiers','Kelime Bilgisi (Vocabulary)','Phrasal Verbs ve Collocations','Cloze Test','Cümle Tamamlama','Anlamca En Yakın Cümle','İngilizce - Türkçe Çeviri','Türkçe - İngilizce Çeviri','Paragraf Soruları','Diyalog Tamamlama','Durum - Tepki (Situation)','Paragraf Tamamlama','Akışı Bozan Cümle'],
  },
};
